releases:
  - name: rediscart
    chart: charts/redis
    values:
      - values/redis-values.yaml
      - appReplicas: "1"
      - volumeName: "redis-cart-data"

  - name: emailservice
    chart: charts/microservice
    values:
      - values/email-service-values.yaml
      - values/lke/emailservice.yaml

  - name: cartservice
    chart: charts/microservice
    values:
      - values/cart-service-values.yaml
      - values/lke/cartservice.yaml

  - name: currencyservice
    chart: charts/microservice
    values:
      - values/currency-service-values.yaml
      - values/lke/currencyservice.yaml

  - name: paymentservice
    chart: charts/microservice
    values:
      - values/payment-service-values.yaml
      - values/lke/paymentservice.yaml

  - name: recommendationservice
    chart: charts/microservice
    values:
      - values/recommendation-service-values.yaml
      - values/lke/recommendationservice.yaml

  - name: productcatalogservice
    chart: charts/microservice
    values:
      - values/productcatalog-service-values.yaml
      - values/lke/productcatalogservice.yaml

  - name: shippingservice
    chart: charts/microservice
    values:
      - values/shipping-service-values.yaml
      - values/lke/shippingservice.yaml

  - name: adservice
    chart: charts/microservice
    values:
      - values/ad-service-values.yaml
      - values/lke/adservice.yaml

  - name: checkoutservice
    chart: charts/microservice
    values:
      - values/checkout-service-values.yaml
      - values/lke/checkoutservice.yaml

  - name: frontendservice
    chart: charts/microservice
    values:
      - values/frontend-values.yaml
      - values/lke/frontend.yaml